export const certificates = [
  {
    id: 'BQMSAVTNAWRJ',
    title: 'Google IT Support',
    issuedDate: 'January 21, 2023',
    orgName: 'Google',
    orgLogo: 'https://i.imgur.com/usgcXsK.png',
    url: 'https://www.coursera.org/account/accomplishments/professional-cert/BQMSAVTNAWRJ',
    pinned: true,
  },
  {
    id: 'G9TW86EEU7LM',
    title: 'Operating Systems and You: Becoming a Power User',
    issuedDate: 'January 12, 2023',
    orgName: 'Google',
    orgLogo: 'https://i.imgur.com/usgcXsK.png',
    url: 'https://www.coursera.org/account/accomplishments/verify/G9TW86EEU7LM',
    pinned: true,
  },
  {
    id: 'CG28SLA9VMQA',
    title: 'Technical Support Fundamentals',
    issuedDate: 'January 7, 2023',
    orgName: 'Google',
    orgLogo: 'https://i.imgur.com/usgcXsK.png',
    url: 'https://www.coursera.org/account/accomplishments/verify/CG28SLA9VMQA',
    pinned: true,
  },
  {
    id: 'XCTQLNKTMAQD',
    title: 'System Administration and IT Infrastructure Services',
    issuedDate: 'January 15, 2023',
    orgName: 'Google',
    orgLogo: 'https://i.imgur.com/usgcXsK.png',
    url: 'https://www.coursera.org/account/accomplishments/verify/XCTQLNKTMAQD',
    pinned: true,
  },
  {
    id: 'BN4B56Y58DJD',
    title: 'The Bits and Bytes of Computer Networking',
    issuedDate: 'January 7, 2023',
    orgName: 'Google',
    orgLogo: 'https://i.imgur.com/usgcXsK.png',
    url: 'https://www.coursera.org/account/accomplishments/verify/BN4B56Y58DJD',
    pinned: true,
  },
  {
    id: 'Z9YZ9SB3JP7U',
    title: 'IT Security: Defense against the digital dark arts',
    issuedDate: 'January 21, 2023',
    orgName: 'Google',
    orgLogo: 'https://i.imgur.com/usgcXsK.png',
    url: 'https://www.coursera.org/account/accomplishments/verify/Z9YZ9SB3JP7U',
    pinned: true,
  },
  {
    id: 'NPTEL22CS53S1370112602095463',
    title: 'Introduction To Internet Of Things',
    issuedDate: 'April 21, 2022',
    orgName: 'Indian Institute of Technology Kharagpur',
    orgLogo: 'https://i.imgur.com/UIdq8Ok.png',
    url: 'https://archive.nptel.ac.in/noc/Ecertificate/?q=NPTEL22CS53S1370112602095463',
    pinned: true,
  },
];
