export const certificates = [
  {
    id: 'BQMSAVTNAWRJ',
    title: 'Google IT Support',
    issuedDate: 'January 21, 2023',
    orgName: 'Google',
    orgLogo: 'https://i.imgur.com/usgcXsK.png',
    url: 'https://www.coursera.org/account/accomplishments/professional-cert/BQMSAVTNAWRJ',
    pinned: true,
  },
  {
    id: 'G9TW86EEU7LM',
    title: 'Operating Systems and You: Becoming a Power User',
    issuedDate: 'January 12, 2023',
    orgName: 'Google',
    orgLogo: 'https://i.imgur.com/usgcXsK.png',
    url: 'https://www.coursera.org/account/accomplishments/verify/G9TW86EEU7LM',
    pinned: true,
  },
  {
    id: 'CG28SLA9VMQA',
    title: 'Technical Support Fundamentals',
    issuedDate: 'January 7, 2023',
    orgName: 'Google',
    orgLogo: 'https://i.imgur.com/usgcXsK.png',
    url: 'https://www.coursera.org/account/accomplishments/verify/CG28SLA9VMQA',
    pinned: true,
  },
  {
    id: 'XCTQLNKTMAQD',
    title: 'System Administration and IT Infrastructure Services',
    issuedDate: 'January 15, 2023',
    orgName: 'Google',
    orgLogo: 'https://i.imgur.com/usgcXsK.png',
    url: 'https://www.coursera.org/account/accomplishments/verify/XCTQLNKTMAQD',
    pinned: true,
  },
  {
    id: 'BN4B56Y58DJD',
    title: 'The Bits and Bytes of Computer Networking',
    issuedDate: 'January 7, 2023',
    orgName: 'Google',
    orgLogo: 'https://i.imgur.com/usgcXsK.png',
    url: 'https://www.coursera.org/account/accomplishments/verify/BN4B56Y58DJD',
    pinned: true,
  },
  {
    id: 'Z9YZ9SB3JP7U',
    title: 'IT Security: Defense against the digital dark arts',
    issuedDate: 'January 21, 2023',
    orgName: 'Google',
    orgLogo: 'https://i.imgur.com/usgcXsK.png',
    url: 'https://www.coursera.org/account/accomplishments/verify/Z9YZ9SB3JP7U',
    pinned: true,
  },
  {
    id: 'NPTEL22CS53S1370112602095463',
    title: 'Introduction To Internet Of Things',
    issuedDate: 'April 21, 2022',
    orgName: 'Indian Institute of Technology Kharagpur',
    orgLogo: 'https://i.imgur.com/UIdq8Ok.png',
    url: 'https://archive.nptel.ac.in/noc/Ecertificate/?q=NPTEL22CS53S1370112602095463',
    pinned: true,
  },
  {
    id: 'NPTEL21MG60S1318004603140397',
    title: 'Ethics In Engineering Practice',
    issuedDate: 'November 16, 2021',
    orgName: 'Indian Institute of Technology Kharagpur',
    orgLogo: 'https://i.imgur.com/UIdq8Ok.png',
    url: 'https://archive.nptel.ac.in/noc/Ecertificate/?q=NPTEL21MG60S1318004603140397',
    pinned: true,
  },
  {
    id: 'XBJT4TXL3GCY',
    title: 'Introduction to Philosophy',
    issuedDate: 'July 13, 2021',
    orgName: 'The University of Edinburgh',
    orgLogo: 'https://i.imgur.com/vaUxRXo.png',
    url: 'https://www.coursera.org/account/accomplishments/verify/XBJT4TXL3GCY',
    pinned: true,
  },
  {
    id: 'nptel21cs32s13190019124945',
    title: 'The Joy Of Computing Using Python',
    issuedDate: 'April 21, 2021',
    orgName: 'Indian Institute of Technology Madras',
    orgLogo: 'https://i.imgur.com/2WyOVjr.png',
    url: 'https://archive.nptel.ac.in/noc/Ecertificate/?q=nptel21cs32s13190019124945',
    pinned: true,
  },
  {
    id: 'NPTEL21HS07S21170037051913',
    title: 'Soft Skill Development',
    issuedDate: 'March 18, 2021',
    orgName: 'Indian Institute of Technology Kharagpur',
    orgLogo: 'https://i.imgur.com/UIdq8Ok.png',
    url: 'https://archive.nptel.ac.in/noc/Ecertificate/?q=NPTEL21HS07S21170037051913',
    pinned: true,
  },
];
